const data = [ // 0: 没去过 1: 去过1次 2: 去过几次 3: 经常去
  { name: 'China', degree: 3 },
  { name: 'United States of America', degree: '0' },
  { name: 'Thailand', degree: '1' },
  { name: 'Malaysia', degree: '1' },
  { name: '安徽', degree: 2 },
  { name: '澳门', degree: 1 },
  { name: '北京', degree: 2 },
  { name: '重庆', degree: 1 },
  { name: '福建', degree: 0 },
  { name: '甘肃', degree: 2 },
  { name: '广东', degree: 3 },
  { name: '广西', degree: 1 },
  { name: '贵州', degree: 1 },
  { name: '海南', degree: 2 },
  { name: '南海诸岛', degree: 0 },
  { name: '河北', degree: 0 },
  { name: '河南', degree: 3 },
  { name: '黑龙江', degree: 0 },
  { name: '湖北', degree: 2 },
  { name: '湖南', degree: 3 },
  { name: '吉林', degree: 0 },
  { name: '江苏', degree: 3 },
  { name: '江西', degree: 2 },
  { name: '辽宁', degree: 0 },
  { name: '内蒙古', degree: 0 },
  { name: '宁夏', degree: 0 },
  { name: '青海', degree: 2 },
  { name: '山东', degree: 2 },
  { name: '山西', degree: 0 },
  { name: '陕西', degree: 1 },
  { name: '上海', degree: 2 },
  { name: '四川', degree: 2 },
  { name: '台湾', degree: 1 },
  { name: '天津', degree: 1 },
  { name: '西藏', degree: 0 },
  { name: '香港', degree: 2 },
  { name: '新疆', degree: 1 },
  { name: '云南', degree: 1 },
  { name: '浙江', degree: 3 },
];

export default data;
